### ISSUE TITLE
Cocoa Pod installing issue 

### ISSUE THREAD

**Issue by AhmadDurrani579** [Cuberto/liquid-swipe#4]
When i am installing this  
Pod is   pod 'liquid-swipe'

This error through 
[!] Unable to find a specification for `liquid-swipe`

**Comment by hamza-faroooq** [comment]
hello @AhmadDurrani579, i had the same issue, just do (pod setup) in your terminal and then again do (pod install).
hope this will helps...

**Comment by askopin** [comment]
@hamza-faroooq did write solution, but you still have an issue try to run `pod install --repo-update`
