### ISSUE TITLE
Not work with me

### ISSUE THREAD

**Issue by GergesEid** [Cuberto/liquid-swipe#9]
It didn't work with me when I write this line in Terminal : pod 'liquid-swipe'
I already write this ( pod 'liquid-swipe' ) line in podfole 
give me that error in Terminal
- liquid-swipe (from `{:get=>"https://github.com/Cuberto/liquid-swipe.get"}`)
- liquid-swipe

**Comment by askopin** [comment]
I have no troubles with installing lib.
According to the log you have given, i suppose that you have some troubles with connection to github
To check it try to clone the repo

**Comment by GergesEid** [comment]
Thanks @askopin it works with me, I clone the repo as you said and the other erro was the minimum deployment target it was ios 9.0 and it must be 9.3 , I solved it.
